### PR TITLE
[BUGFIX] Append ADMCMD_simUser for preview url

### LINKED ISSUE #367: Preview Snippet for page with access rights.
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
The Preview Snippet doesn't work when the page has access rights.

### Please describe what you expected to happen and why.
The Preview Snippet should add the preview parameter **simUser**
ex:  **?ADMCMD_simUser=27** [simulateUserGroup](https://github.com/TYPO3/TYPO3.CMS/blob/10.4/typo3/sysext/frontend/Classes/Middleware/PreviewSimulator.php#L117)

### How can we reproduce this behavior?
1. Create a page
2. add access rights (for group)
3. go back to the Preview Snippet.
4. (The server was not able to access the page to analyse your content, When trying to fetch ..., a 403 status code was received. Please make sure your server can access the page.)

### Technical info
* TYPO3 version: 10.4.6
* Yoast SEO version: 7.0.0

### PR DESCRIPTION
**Pull request by ayacoo**
## Summary

Here a first try.

At my local site it failed because of HTTPS and the certificate. Maybe you can verify this better?

## Test instructions

See issue description

## Quality assurance

* [x] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes #367

### CODE REVIEW

**Comment by haassie** [comment]
Thanks for the pull request. It seems your fork was not up to date before you started this patch. Can you make sure you have the latest update from the master branch in your fork? Now it is giving a merge conflict and also no tests are executed.

**Comment by ayacoo** [comment]
I build an update. I missed that you also support v8. Accordingly the v8 condition was added. Now phpStan is complaining because it doesn't know of the context class. How do you deal with that? I would normally now add a phpStan exception rule.

**Comment by haassie** [comment]
In this case, adding an exception rule is ok.

Favicon is a separate issue I guess.

**Comment by ayacoo** [comment]
Thanks for your answer. I take care of an update and a follow-up PR for the favicon.

**Comment by RinyVT** [comment]
@ayacoo Thank you for the PR!
I have 2 questions:
- Is it correct that this is only a fix for when there are user-group access rights and not starttime? While debugging I found out that in v8 the URL within the PreviewService does not get generated so maybe that's a whole different issue
- The snippet preview now shows the added parameter, maybe this could be filtered again in the `getDataFromContent` method?
Schermafbeelding 2020-12-13 om 15 02 18

**Comment by ayacoo** [comment]
@RinyVT I have added an update regarding the URL output in the backend.

I also have the problem in v8 with the start time. In fact, the request is already empty in the AjaxController. I would assume that TYPO3 simply does not return anything else.

**Comment by RinyVT** [comment]
@ayacoo Thanks for fixing the parameter in the preview box!
On further inspection, I think the implementation of the parameter value is wrong?
Correct me if I'm wrong, but according to this:
https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/frontend/Classes/Middleware/PreviewSimulator.php#L119-L136
The `ADMCMD_simUser` should be the id of the usergroup, not the currently logged in backend user.

I'm not sure how we would need to implement this (since this is admin panel feature to select a user group), but I'm not comfortable with the current implementation.

**Pull request closed without merging**
