### PR TITLE
Use passthrough fields for computed values

### PR DESCRIPTION
**Pull request by YKWeyer**
## Summary

This PR can be summarized in the following changelog entry:

* Change input type for computed `tx_yoastseo_score_readability` and `tx_yoastseo_score_seo` fields to `passthrough`

## Relevant technical choices:

The two mentioned fields are not rendered in the Backend FormEngine. Therefore, the [Passthrough type](https://docs.typo3.org/m/typo3/reference-tca/master/en-us/ColumnsConfig/Type/Passthrough/Index.html#columns-passthrough) seems more adapted than an hidden `input` file.

It also makes sure the fields are not included in `l10nmgr` exports anymore. 

## Test instructions

This PR can be tested by following these steps:

* Log-in to the backend and open the Page module: the YOAST Readability and SEO score icons are properly rendered
* Edit a page: the Readability and SEO score icons are properly rendered
* Open the YOAST Overview module: Readability and SEO columns are filled as usual
* Export a page using the `l10nmgr` extension: `tx_yoastseo_score_readability` and `tx_yoastseo_score_seo` are not included anymore

## Quality assurance

* [x] I have tested this code to the best of my abilities
* [ ] <del>I have added unittests to verify the code works as intended</del> This is a configuration change

### CODE REVIEW

**Comment by RinyVT** [comment]
Thanks for the PR!
As we're working on a new version 8, I will set this to `feature/v8` as version 7 is currently in high-priority bugfix and this change will be merged into master at the moment.

**Comment by YKWeyer** [comment]
Hi @RinyVT ,

I just rebased both my MRs onto `feature/v8`. Let me know if anything needs to be changed :+1:

**Review by RinyVT — APPROVED** [review]

**Comment by RinyVT** [comment]
I have tested the changes in CMS9, CMS10 and CMS11 and everything still seems to work.
I think this is leftover code from previous analyzing / previewing mechanisms where we've worked with hidden fields.

https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/Classes/Form/Element/SnippetPreview.php#L230-L232
Here the field selectors are set for these hidden fields but these selectors not used anymore as far as I can tell.

@haassie What do you think? We could merge this and I'll take care of removing all the leftover / unnecessary code.

**Comment by haassie** [comment]
Well, I guess this is a left-over from historical versions. Before this hidden field was used to save the scores into the database. But this is now done by AJAX. So I guess this can be done safely. You might however also want to remove those left-overs as mentioned by @RinyVT

**Pull request merged**
