### PR TITLE
Please update pages.php

### PR DESCRIPTION
**Pull request by prathers**
In your commit [f688528], you use char while the db-field is an integer. I suggest this as a solution.

## Quality assurance

* [x ] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

### CODE REVIEW

**Comment by haassie** [comment]
By not using the specific renderType, the functionality of updating the analysis will be gone. We need to have that specific renderType.

**Comment by haassie** [comment]
We will check after the new release if we can optimize this. Do you get an error message somewhere with this?

**Comment by prathers** [comment]
Point taken Richard. But I get an error, when creating a new page
`2: SQL error: 'Incorrect integer value: '' for column 'tx_yoastseo_cornerstone' at row 1' (pages:NEW5cb07f82a6815006252963)`
TYPO3 v9.5.5

**Comment by prathers** [comment]
We updated the ext to latest - problem seems to be solved

**Comment by haassie** [comment]
Good to hear! If you get any new warnings / errors, please let us know!

**Pull request closed without merging**
