### PR TITLE
[FEATURE] Support canonical links for pages with cHashes.

### PR DESCRIPTION
**Pull request by websi**
For example the news details page

### CODE REVIEW

**Comment by haassie** [comment]
Are you using the Yoast plugin for news detail pages? I wouldn't recommend that at the moment or do you have excluded the page title and og tags? These are set by the news extension itself on the detail page.

**Comment by websi** [comment]
Yes we use the plugin on every page.
We can deactivate it on a news detail page. For that we need 1f9532edf777156ddad9a64083526d8a0e0316a9. But this is not released.

But, the canonical link was not set by news or any other extension with detail views.

The news extension generate no title tag. It only set the field `altPageTitle`, which can use for title tag rendering. See https://github.com/georgringer/news/blob/master/Classes/ViewHelpers/TitleTagViewHelper.php
We can use something like that. https://docs.typo3.org/typo3cms/extensions/news/6.1.1/AdministratorManual/BestPractice/IntegrationWithTypoScript/Index.html#add-html-to-the-header-part-in-the-detail-view
But the yoast plugin can use the `altPageTitle` attribute. So no condition at TypoScript needed.
And in our environment, the editor can create more than one news detail page. So a simple TypoScript condition do not work for us.

We also need a solution to deactivate not the complete rendering of the plugin.
For news we only want to deactivate the og tags.

**Comment by websi** [comment]
For meta tags you should use the page rendering API from TYPO3. The news extension use it also.
https://github.com/georgringer/news/blob/master/Classes/ViewHelpers/MetaTagViewHelper.php

That prevent duplication of meta tags on the page.

**Comment by haassie** [comment]
In version 2 the rendering of metatags will be different. Therefor I will close this pull request.

**Pull request closed without merging**
