### PR TITLE
[BUGFIX] Only load extension configuration for loaded extenions

### PR DESCRIPTION
**Pull request by websi**

### CODE REVIEW

**Comment by websi** [comment]
Can anyone please give feedback? @haassie ?

**Comment by nito-web** [comment]
Or just leave it to the people to add `tx_yoastseo_focuskeyword varchar(32) DEFAULT '' NOT NULL, ` to the tables if needed and don't create useless tables.

**Comment by haassie** [comment]
Sorry. PR came during my holiday. Will check it next week.

________________________________

**Comment by haassie** [comment]
Looks like a good solution! But how about we remove the news and cal part in the extension (of course in a major version) and provide snippets and an separate extension to integrate into the other plugins?

**Comment by websi** [comment]
That's  a architecture decision you must have to meet.
With separate extension you have a small base extension, but more work for the maintenance of all the additional extensions.

**Comment by haassie** [comment]
We will do that. Will close this PR and the EXT:news and EXT:cal table creation will be removed in next major version.

**Pull request closed without merging**
