### PR TITLE
[BUGFIX] Do not render entries if location is empty

### LINKED ISSUE #228: Sitemap should not render records on disabled detail pages
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
Because of my misconfiguration (set a disabled page) the sitemap.xml render x empty entries. The loc Tag is empty because
$cObject->typoLink_URL($typoLinkConf); don't find the target detail page.

https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/release/3.0/Classes/UserFunc/SitemapXml.php#L148

### Please describe what you expected to happen and why.
Sitemap shouldn't render hidden detail pages (here records) and add a log entry. No exception of course ;-)

### How can we reproduce this behavior?
1. Build a standard config for "other" plugins
2. Set the detailPid to a hidden and disabled page

### Technical info
* TYPO3 version: 8.7.20
* Yoast SEO version: 3.0.4
* Relevant extensions in case of a bug: news

### PR DESCRIPTION
**Pull request by ayacoo**
## Test instructions

This PR can be tested by following these steps:

* Add a config for "other" plugins, e.g. news, and disable the detail page.

## Quality assurance

* [x] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

## Fixes
#228

### CODE REVIEW

**Comment by ayacoo** [comment]
You would create your own news.xml, in which this if condition must be purely.

The "problem" is that you have to expect from the integrators that they can also customize the templates.  If that's okay for you, at least the documentation would have to be adjusted.

**Comment by haassie** [comment]
Fixed by #236

**Comment by haassie** [comment]
Sorry, wrong close

**Comment by haassie** [comment]
Well actually, it is fixed by #236.

**Pull request closed without merging**
